[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[build]
  command = "echo Building Function"
  functions = "./src"
  targetPort = 5000
  publish = "./dist"

[dev]
  command = "npm run dev"
  targetPort = 5000
  functions = "./functions"
  publish = "./dist"