[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[build]
  command = "netlify functions:build"
  functions = "./functions"
  targetPort = 5000
  publish = "./dist"

[dev]
  command = "npm run dev"
  targetPort = 5000
  functions = "./functions"
  publish = "./dist"