[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[build]
  command = "echo Building Function"
  functions = "./src"
  publish = "./dist"

[dev]
  command = "npm run dev"
  targetPort = 5000
  functions = "./functions"
  publish = "./dist"

[[redirects]]
  force = true
  from = "/api/datasheet/*"
  status = 200
  to = "/.netlify/functions/api/datasheet/:splat"